version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
    tty: true
    stdin_open: true
    restart: unless-stopped

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - mc
    restart: unless-stopped
    environment:
      DOMAINS: 'mc.ampis.org'
      STAGE: 'production'
      FORCE_RENEW: 'true'
    volumes: 
      - https-portal-data:/var/lib/https-portal
      - /data/https-portal/vhosts:/var/www/vhosts
volumes:
  https-portal-data:
